env:
  FORCE_COLOR: 1
  GIT_TERMINAL_PROMPT: 0
steps:
  - label: Build chromium - Mac (x86)
    key: build-chromium-mac-x86_64
    timeout_in_minutes: 60
    plugins:
      - thedyrt/skip-checkout#v0.1.1:
          cd: /Users/administrator/chromium/src
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            BUILDEVENT_APIKEY: honeycomb-api-key
            BUILDEVENT_BUILDKITE_API_TOKEN: buildkite-api-token-honeycomb-build-events
      - replayio/buildevents#adb8a05: null
    commands:
      - be_cmd git-fetch-all -- git fetch --all
      - be_cmd git-reset-branch -- git reset --hard origin/$BUILDKITE_BRANCH
      - >-
        be_cmd update-all-repos -- node
        replay_build_scripts/update-all-repos.mjs
      - pushd ../backend
      - be_cmd buck2-kill -- buckle kill
      - >-
        be_cmd buck2-build -- buckle build --console simple //:chromium
        --target-platforms=//:macos-x86_64
      - popd
    env:
      GOMA_SERVER_HOST: simpsonite.goma.engflow.com
      GOMACTL_USE_PROXY: false
      RECORD_REPLAY_BACKEND_DIR: /Users/administrator/chromium/backend
      DRIVER_REVISION: bfa48f25922d
    agents:
      - runtimeType=chromiumbuild
      - os=macos
      - queue=runtime
    artifact_paths:
      - build_id/macOS/x86_64/**
    depends_on:
      - build-driver-linker
  - label: Build chromium - Mac (arm64)
    key: build-chromium-mac-arm64
    timeout_in_minutes: 60
    plugins:
      - thedyrt/skip-checkout#v0.1.1:
          cd: /Users/administrator/chromium/src
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            BUILDEVENT_APIKEY: honeycomb-api-key
            BUILDEVENT_BUILDKITE_API_TOKEN: buildkite-api-token-honeycomb-build-events
      - replayio/buildevents#adb8a05: null
    commands:
      - be_cmd git-fetch-all -- git fetch --all
      - be_cmd git-reset-branch -- git reset --hard origin/$BUILDKITE_BRANCH
      - >-
        be_cmd update-all-repos -- node
        replay_build_scripts/update-all-repos.mjs
      - pushd ../backend
      - be_cmd buck2-kill -- buckle kill
      - >-
        be_cmd buck2-build -- buckle build --console simple //:chromium
        --target-platforms=//:macos-arm64
      - popd
    env:
      GOMA_SERVER_HOST: simpsonite.goma.engflow.com
      GOMACTL_USE_PROXY: false
      REPLAY_BUILD_ARM: true
      RECORD_REPLAY_BACKEND_DIR: /Users/administrator/chromium/backend
      DRIVER_REVISION: bfa48f25922d
    agents:
      - runtimeType=chromiumbuild
      - os=macos
      - queue=runtime
    artifact_paths:
      - build_id/macOS/arm64/**
    depends_on:
      - build-driver-linker
  - trigger: testing-runtime-e2e
    label: ':hammer: Trigger Runtime Tests'
    depends_on:
      - build-chromium-mac-x86_64
      - build-chromium-mac-arm64
      - build-driver-linker
    build:
      branch: dominik/run-2965-fe-throws-could-not-find-object-id-1
  - trigger: build-driver-linker
    key: build-driver-linker
    label: Build Driver/Linker
    build:
      branch: dominik/run-2965-fe-throws-could-not-find-object-id-1
