env:
  FORCE_COLOR: 1
  GIT_TERMINAL_PROMPT: 0
steps:
  - trigger: testing-runtime-e2e
    label: ':hammer: Trigger Runtime Tests'
    depends_on: []
    build:
      branch: dominik/run-3068-js-divergences-spike
