# Build arguments go here.
# See "gn args <out_dir> --list" for available build arguments.

use_siso = true
use_remoteexec = true
use_reclient = false

symbol_level = 1
is_debug = false
dcheck_always_on = false # disable dchecks

use_allocator = "none"
use_allocator_shim = false
enable_backup_ref_ptr_support = false
